/* translation of file "Frontend/Parser/formula_unparse.k" */
/* generated by:
 *  @(#)$Author: Kimwitu++ version 2.3.13 (C) 1998-2008 Humboldt-Universitaet zu Berlin $
 */
#define KC_FUNCTIONS_formula_unparse

#include <stdlib.h>
#include "ast-system-k.h"
#include "formula_unparse.h"

namespace kc {

#ifndef KC_TRACE_PROVIDED
#define KC_TRACE_PROVIDED(COND,FILE,LINE,NODE) COND
#endif


} // namespace kc
