/* translation of file "Frontend/Parser/formula_rewrite.k" */
/* generated by:
 *  @(#)$Author: Kimwitu++ version 2.3.13 (C) 1998-2008 Humboldt-Universitaet zu Berlin $
 */
#ifndef KC_FUNCTIONS_formula_rewrite_HEADER
#define KC_FUNCTIONS_formula_rewrite_HEADER
#include "ast-system-k.h"    // in case a user forgets


namespace kc {

} // namespace kc

#endif // !  KC_FUNCTIONS_formula_rewrite_HEADER

